import { Toaster } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";

import ConvexClientProvider from "./ConvexClientProvider";
import Provider from "./provider";
import "./globals.css";

export const metadata = {
  title: "INHUB",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ClerkProvider>
          <ConvexClientProvider>
            <Provider>
              {children}
            </Provider>
            <Toaster />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
