"use client";

import React, { useEffect, useState } from "react";
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackFileExplorer,
} from "@codesandbox/sandpack-react";
import Lookup from "@/data/Lookup";
import { Loader2Icon, Github, Link as LinkIcon, Copy } from "lucide-react";
import { toast } from "sonner";
import { useParams } from "next/navigation";

/**
 * CodeView (updated)
 *
 * - Robust changeBranch: prompts for repo and branch if missing; posts full payload to /api/github-rename.
 * - Prompts user for meaningful repo name if missing before publishing.
 * - Saves metadata after user changes.
 */

// sanitize branch/repo names
function slugify(input) {
  if (!input) return "";
  return String(input)
    .trim()
    .toLowerCase()
    .replace(/[_\s]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

// small delay helper
function wait(ms) {
  return new Promise((res) => setTimeout(res, ms));
}

function CodeView({ projectFiles }) {
  const { id } = useParams();

  const [files, setFiles] = useState(Lookup.DEFAULT_FILE ?? {});
  const [loading, setLoading] = useState(false);

  // repo info state
  const [repoName, setRepoName] = useState("");
  const [repoUrl, setRepoUrl] = useState("");
  const [repoBranch, setRepoBranch] = useState("main");

  useEffect(() => {
    if (projectFiles && Object.keys(projectFiles).length) {
      setFiles(projectFiles);
    }
  }, [projectFiles]);

  useEffect(() => {
    if (!id) return;
    const loadRepoInfo = async () => {
      try {
        const res = await fetch(`http://localhost:3000//api/projects/${id}`);
        if (!res.ok) {
          toast("Failed to load project metadata");
          return;
        }
        const data = await res.json();
        setRepoUrl(data.githubRepoUrl || "");
        setRepoName(data.githubRepoName || "");
        setRepoBranch(data.githubBranch || "main");
      } catch (err) {
        console.error("loadRepoInfo error", err);
        toast("Unexpected error loading repo info");
      }
    };
    loadRepoInfo();
  }, [id]);

  const saveRepoMetadata = async (meta = {}) => {
    if (!id) return;
    try {
      await fetch(`http://localhost:3000//api/projects/${id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(meta),
      });
    } catch (err) {
      console.error("saveRepoMetadata error", err);
    }
  };

  const sanitizeRepoName = (input) => {
    if (!input || typeof input !== "string") return "";
    let s = input.trim().toLowerCase();
    s = s.replace(/[_\s]+/g, "-");
    s = s.replace(/[^a-z0-9-]/g, "");
    s = s.replace(/-+/g, "-");
    s = s.replace(/^-+|-+$/g, "");
    if (s.length > 60) s = s.slice(0, 60);
    return s || "";
  };

  const promptEditRepoName = async () => {
    const current = repoName || "";
    const userInput = window.prompt(
      "Enter repository name (letters, numbers, hyphen). Example: my-app, user-repo",
      current
    );
    if (!userInput) return;
    const sanitized = sanitizeRepoName(userInput);
    if (!sanitized) {
      toast("Invalid repository name after sanitization");
      return;
    }
    setRepoName(sanitized);
    await saveRepoMetadata({ githubRepoName: sanitized });
    toast(`Repository name set to ${sanitized}`);
  };
const changeBranch = async () => {
  const newBranch = window.prompt("Enter new branch name:", repoBranch || "main");
  if (!newBranch) return;

  let repoNameToUse = repoName;
  if (!repoNameToUse) {
    toast("Set repository name first");
    return;
  }

  setLoading(true);
  try {
    const res = await fetch("/api/github-branch", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        repoName: repoNameToUse, // "owner/repo" OR "repo" (GITHUB_OWNER used)
        branch: newBranch,
        baseBranch: "main", // optional; handler will fallback sensibly
      }),
    });

    const data = await res.json().catch(() => null);
    if (!res.ok) {
      toast(data?.error || "Failed to create or switch branch");
      return;
    }

    // success
    setRepoBranch(newBranch);
    saveRepoMetadata({ githubBranch: newBranch });
    toast(`Switched to branch: ${newBranch}`);
  } catch (err) {
    console.error("changeBranch error", err);
    toast("Unexpected error switching branch");
  } finally {
    setLoading(false);
  }
};

    

  /**
   * publishToGitHub
   * - Ensure meaningful repo name if auto-generated or missing.
   * - Ensure branch exists if repo exists (via /api/github-branch).
   * - Call /api/github-publish with branch.
   */
  const publishToGitHub = async () => {
    try {
      if (!Object.keys(files).length) {
        toast("No files to publish to GitHub");
        return;
      }

      let repoNameToUse = repoName || "";

      const isAutoGenerated = (name) => {
        if (!name) return true;
        return /^ai-workspace(-|_)/i.test(name) || /^ai-workspace/.test(name);
      };

      if (!repoNameToUse || isAutoGenerated(repoNameToUse)) {
        const userInput = window.prompt(
          "Enter a repository name for this project (this will be used on GitHub). Example: my-cool-app",
          repoNameToUse || ""
        );
        if (!userInput) {
          toast("Publish cancelled: repository name required");
          return;
        }
        const sanitized = sanitizeRepoName(userInput);
        if (!sanitized) {
          toast("Invalid repository name after sanitization");
          return;
        }
        repoNameToUse = sanitized;
        setRepoName(sanitized);
        await saveRepoMetadata({ githubRepoName: sanitized });
      }

      setLoading(true);

      // If we already have a repo on the UI (repoUrl or repoName present),
      // ensure branch exists remotely before publishing.
      if (repoUrl || repoName) {
        try {
          const ensureRes = await fetch("/api/github-branch", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              repoName: repoNameToUse,
              branch: repoBranch,
              baseBranch: "main",
            }),
          });

          if (!ensureRes.ok && ensureRes.status !== 409) {
            const errData = await ensureRes.json().catch(() => null);
            toast(errData?.error || "Failed to ensure branch exists");
            setLoading(false);
            return;
          }
        } catch (err) {
          console.error("ensure branch error", err);
          toast("Failed to ensure branch exists");
          setLoading(false);
          return;
        }
      }

      const res = await fetch("/api/github-publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoName: repoNameToUse, files, branch: repoBranch }),
      });

      const data = await res.json().catch(() => null);
      if (!data || !data.success) {
        toast(data?.error || "GitHub publish failed");
        return;
      }

      setRepoUrl(data.repoUrl || `https://github.com/${data.repoName || repoNameToUse}`);
      setRepoName(data.repoName || repoNameToUse);

      await saveRepoMetadata({
        githubRepoName: data.repoName || repoNameToUse,
        githubRepoUrl: data.repoUrl || undefined,
        githubBranch: repoBranch,
      });

      toast("Published successfully!");
      if (data.repoUrl) window.open(data.repoUrl, "_blank");
    } catch (error) {
      console.error(error);
      toast("Unexpected error");
    } finally {
      setLoading(false);
    }
  };

  const openRepo = () => {
    if (!repoUrl) return toast("No repo URL available");
    window.open(repoUrl, "_blank");
  };

  const copyRepoUrl = async () => {
    if (!repoUrl) return toast("No repo URL to copy");
    try {
      await navigator.clipboard.writeText(repoUrl);
      toast("Repository URL copied to clipboard");
    } catch (err) {
      toast("Unable to copy URL");
    }
  };

  return (
    <div className="relative">
      {/* HEADER */}
      <div className="codeview-header w-full flex items-center justify-between">
        <div className="font-semibold text-white/70">Code Editor</div>

        <div className="flex items-center gap-3">
          {/* repo display */}
          <div className="repo-info text-sm text-white/70 flex items-center gap-2">
            {repoName ? (
              <>
                {repoUrl ? (
                  <a
                    href={repoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="repo-link underline-offset-2 hover:underline"
                  >
                    {repoName}
                  </a>
                ) : (
                  <span>{repoName}</span>
                )}

                <button
                  onClick={openRepo}
                  title="Open repository"
                  className="repo-action ml-2 px-2 py-1 rounded"
                >
                  <LinkIcon className="w-4 h-4" />
                </button>

                <button
                  onClick={copyRepoUrl}
                  title="Copy repository URL"
                  className="repo-action px-2 py-1 rounded"
                >
                  <Copy className="w-4 h-4" />
                </button>

                <button
                  onClick={promptEditRepoName}
                  title="Edit repository name"
                  className="repo-action px-2 py-1 rounded"
                >
                  <span className="text-xs">Rename</span>
                </button>

                <button
                  onClick={changeBranch}
                  title="Change branch"
                  className="repo-action px-2 py-1 rounded"
                >
                  <span className="text-xs">{repoBranch}</span>
                </button>
              </>
            ) : (
              <>
                <span className="text-white/40">No repo</span>

                <button
                  onClick={() => {
                    const newBranch = window.prompt("Enter branch name:", repoBranch || "main");
                    if (!newBranch) return;
                    setRepoBranch(newBranch);
                    saveRepoMetadata({ githubBranch: newBranch });
                    toast(`Branch set to ${newBranch}`);
                  }}
                  title="Set branch"
                  className="repo-action px-2 py-1 rounded ml-2"
                >
                  <span className="text-xs">{repoBranch}</span>
                </button>

                <button
                  onClick={promptEditRepoName}
                  title="Set repo name before publishing"
                  className="repo-action px-2 py-1 rounded ml-2"
                >
                  <span className="text-xs">Set repo name</span>
                </button>
              </>
            )}
          </div>

          {/* GitHub publish */}
          <button onClick={publishToGitHub} className="codeview-publish">
            <Github className="w-4 h-4" /> Publish to GitHub
          </button>
        </div>
      </div>

      <SandpackProvider
        files={files}
        template="react"
        theme="dark"
        customSetup={{
          dependencies: { ...Lookup.DEPENDANCY },
        }}
        options={{ externalResources: ["https://cdn.tailwindcss.com"] }}
      >
        <SandpackLayout style={{ height: "80vh" }}>
          <SandpackFileExplorer style={{ height: "80vh" }} />
          <SandpackCodeEditor style={{ height: "80vh" }} />
        </SandpackLayout>
      </SandpackProvider>

      {/* LOADING SPINNER */}
      {loading && (
        <div className="codeview-loading-overlay absolute top-0 w-full h-full flex flex-col gap-4 justify-center items-center">
          <Loader2Icon className="animate-spin w-10 h-10 text-white" />
          <h2 className="text-white/80">Processing...</h2>
        </div>
      )}

      {/* STYLES */}
      <style>{`
        .codeview-header {
          background: #0c1120;
          padding: 10px 16px;
          border-radius: 10px;
          border: 1px solid rgba(255,255,255,0.08);
          margin-bottom: 10px;
        }
        .codeview-publish {
          background: #1f1f1f;
          border: 1px solid rgba(255,255,255,0.08);
          padding: 8px 14px;
          border-radius: 8px;
          display: flex;
          gap: 8px;
          align-items: center;
          color: white;
        }
        .codeview-publish:hover {
          opacity: .85;
        }
        .codeview-loading-overlay {
          backdrop-filter: blur(4px);
          background: rgba(0,0,0,0.45);
          z-index: 50;
        }
        .repo-info a {
          color: rgba(255,255,255,0.85);
          text-decoration: none;
        }
        .repo-info a:hover {
          text-decoration: underline;
        }
        .repo-action {
          background: rgba(255,255,255,0.03);
          border: 1px solid rgba(255,255,255,0.04);
          margin-left: 6px;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          padding: 6px;
        }
        .repo-action:hover { opacity: .9 }
      `}</style>
    </div>
  );
}

export default CodeView;